### PR TITLE
Implement save content state for Documentation tool

### PR DESCRIPTION
**Pull request by ilukanets**
This PR implements Save user data for Documentation tool.

More info is here https://h5p.org/node/49815

### CODE REVIEW

**Comment by BV52** [comment]
Hi ilukanets,

Thank you very much for your contribution. I have created a task to review this and you can follow it [here](https://h5ptechnology.atlassian.net/browse/HFP-1965).

-BV52

**Comment by timothyylim** [comment]
Hi @ilukanets , this is pretty good work so far. I have two requests before I can merge this in:

1. Each library should be resumed independently. That means each page instance should be responsible for saving and restoring it's own data instead of the documentation tool library. 

2. All the different types of page instances should have this feature, not just 'standard pages'

Good work so far 👍

**Comment by ilukanets** [comment]
Hello, @timothyylim 
Thanks for your feedback. I have some time to work on this. But I have few questions on this.

1. Should data be stored in db for each page instance separately and not for Documentation tool object?
2. Does the logic should be implemented in each page type repository?
3. What page types have to be covered?

It would be great to get your response as soon as possible. 
Best regards.

**Comment by timothyylim** [comment]
Hi @ilukanets 
1. Yes, the data should be stored separately for each page 
2. Yes, the logic should be implemented for each page type repostory.
3. All of the ones which require input from the user: Standard page, Goals page and Goals Assessment

Is this reasonable, @thomasmars ?

**Comment by ilukanets** [comment]
Hi, @timothyylim
I've created few new pull requests for this feature. Here are links:

https://github.com/h5p/h5p-documentation-tool/pull/10
https://github.com/h5p/h5p-standard-page/pull/10
https://github.com/h5p/h5p-goals-page/pull/9
https://github.com/h5p/h5p-goals-assessment-page/pull/7

Please take a look on them.
Best regards.

**Pull request closed without merging**
