### PR TITLE
Implement api for saving pages instances state

### PR DESCRIPTION
**Pull request by ilukanets**
This PR implements Save user data for Documentation tool.
More info is here https://h5p.org/node/49815

Please see PR https://github.com/h5p/h5p-documentation-tool/pull/8

### CODE REVIEW

**Comment by ilukanets** [comment]
There are also related PRs:

https://github.com/h5p/h5p-standard-page/pull/10
https://github.com/h5p/h5p-goals-page/pull/9
https://github.com/h5p/h5p-goals-assessment-page/pull/7

**Comment by Wmsmckay** [comment]
Just wondering if this is this going to be merged soon. I would like to use the save content state with the documentation tool and it looks like everything has been completed. Please let me know if there are any updates.

**Comment by kevinmoilar** [comment]
**Please** merge these! It is super painful for users to enter their work only to realize it wasn't stored.

**Comment by ilukanets** [comment]
@Wmsmckay @kevinmoilar thanks for your interest of this.
@icc Any updates? We at Eurekos are using this for a time as a patch, and it works great. It would be nice to get support of saving state in the official version.

**Comment by Wmsmckay** [comment]
@ilukanets @kevinmoilar The last email I received said all the developers are focusing on the H5P OER hub and after that they will focus on PRs. Hopefully there is enough interest generated that this will be a high priority. @ilukanets How did you set this up to use in a production environment? If we have to wait much longer I'd love to have something working soon.

**Comment by fnoks** [comment]
I first have to apologize this hasn't been handled several years ago.

I have had a look at it now, and for me it seems to introduce a new way of setting the state through a setPreviousState function. This is not how this is done for any other content type. I.e : the previous state should be passed into newRunnable (through extras.previousState) when creating the "sub content" instances.

**Comment by fnoks** [comment]
Fixed in #46 . Therefore closing this one

**Pull request closed without merging**
